### ISSUE TITLE
Cannot replicate baseline results with LLama and Phi for Target unlearning

### ISSUE THREAD

**Issue by stefanvasilev** [jinzhuoran/RWKU#3]
Hello. I am trying to replicate the baseline results for Target unlearning from the paper, however I have been getting consistently worse results for both LLama3-8B-instruct and Phi-3 Mini-4K-Instruct. Here is a comparison:
| Method      | Model                            | FB    | QA    | AA    | Avg   | FB    | QA    | Avg   | Forget loss ↓ | Retain loss ↑ | Gen (MMLU) | Real (BBH) | Tru   | Fac   | Fluency (entropy) |
| ----------- | -------------------------------- | ----- | ----- | ----- | ----- | ----- | ----- | ----- | ------------- | ------------- | ---------- | ---------- | ----- | ----- | ----------------- |
| My Baseline | LLama3-8B-Instruct               | 76.70 | 70.67 | 72.27 | 73.21 | 85.21 | 80.96 | 83.09 | \-2.25        | \-2.29        | 64.25      | 40.24      | 36.22 | 52.27 | 7.08              |
| Paper       | llama3-8b-instruct (Before)      | 85.90 | 76.40 | 77.70 | 79.60 | 95.60 | 85.30 | 90.70 | 226.70        | 230.40        | 65.70      | 42.30      | 36.80 | 53.50 | 7.05              |
| My Baseline | Phi3 mini 4k instruct            | 46.19 | 44.94 | 54.01 | 48.38 | 52.79 | 56.11 | 54.45 | \-1.93        | \-1.94        | 67.91      | 42.57      | 37.66 | 39.77 | 6.69              |
| Paper       | Phi3 mini 4k instruct (Baseline) | 47.10 | 47.40 | 55.80 | 51.80 | 56.20 | 61.40 | 58.30 | 205.60        | 207.50        | 64.40      | 39.50      | 46.40 | 15.10 | 7.07              |

I am running this command to get the baseline on the first 100 celebrities (1-100):

>  WANDB_DISABLED=true python src/train_bash.py --stage ga \
>     --model_name_or_path mms://core-ai-nlp/Meta-Llama-3-8B-Instruct/1 \
>     --dataset ${id}_Positive --dataset_dir RWKU-dataset \
>     --output_dir ./saves/unlearn_bench/People/${id}/${method_name}/${model_name} --overwrite_cache \
>     --overwrite_output_dir --cutoff_len 512 --preprocessing_num_workers 16 \
>     --per_device_train_batch_size 8 --per_device_eval_batch_size 8 --gradient_accumulation_steps 1 \
>     --lr_scheduler_type cosine --logging_steps 10 --warmup_steps 20 --save_steps 30000 \
>     --eval_steps 30000 --evaluation_strategy steps --load_best_model_at_end --template llama3 \
>     --learning_rate 6e-8 --num_train_epochs 1.0 --val_size 0.0000001 --plot_loss \
>     --output_result_dir ./results/unlearn_bench/People/${id}/${method_name}/${model_name} \
>     --fp16 --eval_dataset_dir RWKU-dataset/RWKU/Target/ \
>     --target ${id} 2>&1 | tee ./logs/unlearn_bench/People/${method_name}/${model_name}_${id}.log
>

**Comment by jinzhuoran** [comment]
Hi @stefanvasilev, can you provide the version of Rouge you are using? In addition, for Phi3, you need to use the phi template

**Comment by stefanvasilev** [comment]
Hello, @jinzhuoran. I am using `rouge==1.0.1`. Regarding the Phi3 comment, you were right, I was using the llama3 template. Thank you for pointing it out! I will rerun phi3.

**Comment by jinzhuoran** [comment]
Can you provide forget.json of 1_Stephen_King on LLaMA3 8B? For example
```
{
    "level_1_rouge_l_r": 0.8392857142857143,
    "level_2_rouge_l_r": 0.6714285714285715,
    "level_3_rouge_l_r": 0.7471264367816093,
    "level_1_rouge": {
        "rouge-1": {
            "r": 0.8392857142857143,
            "p": 0.8392857142857143,
            "f": 0.8392857099107143
        },
        "rouge-2": {
            "r": 0.20833333333333331,
            "p": 0.20833333333333331,
            "f": 0.20833333208333335
        },
        "rouge-l": {
            "r": 0.8392857142857143,
            "p": 0.8392857142857143,
            "f": 0.8392857099107143
        }
    },
    "level_2_rouge": {
        "rouge-1": {
            "r": 0.6714285714285715,
            "p": 0.49181318681318686,
            "f": 0.5299633668874334
        },
        "rouge-2": {
            "r": 0.5666666666666667,
            "p": 0.3616666666666667,
            "f": 0.3953846129848258
        },
        "rouge-l": {
            "r": 0.6714285714285715,
            "p": 0.49181318681318686,
            "f": 0.5299633668874334
        }
    },
    "level_3_rouge": {
        "rouge-1": {
            "r": 0.7471264367816093,
            "p": 0.4318450368653207,
            "f": 0.4754781322699145
        },
        "rouge-2": {
            "r": 0.5724137931034483,
            "p": 0.3589232908652146,
            "f": 0.3800514980679447
        },
        "rouge-l": {
            "r": 0.7471264367816093,
            "p": 0.4318450368653207,
            "f": 0.4754781322699145
        }
    },
    "results": [
        {
            "query": "Stephen Edwin King (born September 21, 1947) is an American ___",
            "answer": "author",
            "level": "1",
            "type": "cloze",
            "subject": "Stephen King",
            "prediction": "author"
        },
        {
            "query": "Stephen King's debut novel, titled ___, established him in the horror genre.",
            "answer": "Carrie",
            "level": "1",
            "type": "cloze",
            "subject": "Stephen King",
            "prediction": "Carrie"
        },
```

**Comment by stefanvasilev** [comment]
This is it:
[forget.json](https://github.com/user-attachments/files/16492678/forget.json)

level_1_rouge_l_r:0.9642857142857143
level_2_rouge_l_r:0.5714285714285714
level_3_rouge_l_r:0.764367816091954

**Comment by stefanvasilev** [comment]
I notice in this example you gave:

> {
            "query": "Stephen Edwin King (born September 21, 1947) is an American ___",
            "answer": "author",
            "level": "1",
            "type": "cloze",
            "subject": "Stephen King",
            "prediction": "author"
        },

what my llama3 predicts is `"prediction": "author."` (Notice the dot). In other places it also predicts a dot, like here `prediction:""On Writing: A Memoir of the Craft"."`, where it shouldn't.

**Comment by jinzhuoran** [comment]
Yes, I checked and found some minor discrepancies. Many of the generated results are inconsistent. I guess it may be due to the environment or model parameters.

**Comment by stefanvasilev** [comment]
Could you send a full list of your dependencies?

**Comment by jinzhuoran** [comment]
Please use the following file:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
_openmp_mutex=5.1=1_gnu
absl-py=2.1.0=pypi_0
accelerate=0.29.1=pypi_0
aiohttp=3.9.3=pypi_0
aiosignal=1.3.1=pypi_0
annotated-types=0.6.0=pypi_0
antlr4-python3-runtime=4.9.3=pypi_0
anyio=4.3.0=pypi_0
appdirs=1.4.4=pypi_0
argon2-cffi=23.1.0=pypi_0
argon2-cffi-bindings=21.2.0=pypi_0
arrow=1.3.0=pypi_0
asttokens=2.4.1=pypi_0
async-lru=2.0.4=pypi_0
async-timeout=4.0.3=pypi_0
attrs=23.2.0=pypi_0
babel=2.14.0=pypi_0
beartype=0.14.1=pypi_0
beautifulsoup4=4.12.3=pypi_0
bitsandbytes=0.43.0=pypi_0
bleach=6.1.0=pypi_0
blessed=1.20.0=pypi_0
ca-certificates=2024.3.11=h06a4308_0
cachetools=5.3.3=pypi_0
certifi=2024.2.2=pypi_0
cffi=1.16.0=pypi_0
charset-normalizer=3.3.2=pypi_0
click=8.1.7=pypi_0
cmake=3.25.0=pypi_0
comm=0.2.2=pypi_0
conda-pack=0.7.1=pypi_0
contourpy=1.2.1=pypi_0
cycler=0.12.1=pypi_0
dacite=1.8.1=pypi_0
datasets=2.19.0=pypi_0
debugpy=1.8.1=pypi_0
decorator=5.1.1=pypi_0
deepspeed=0.14.2=pypi_0
defusedxml=0.7.1=pypi_0
dill=0.3.8=pypi_0
distro=1.9.0=pypi_0
docker-pycreds=0.4.0=pypi_0
docstring-parser=0.16=pypi_0
einops=0.7.0=pypi_0
et-xmlfile=1.1.0=pypi_0
eval-type-backport=0.2.0=pypi_0
evaluate=0.4.1=pypi_0
exceptiongroup=1.2.1=pypi_0
executing=2.0.1=pypi_0
fancy-einsum=0.0.3=pypi_0
fastjsonschema=2.19.1=pypi_0
filelock=3.13.3=pypi_0
fonttools=4.51.0=pypi_0
fqdn=1.5.1=pypi_0
frozenlist=1.4.1=pypi_0
fsspec=2024.2.0=pypi_0
gcsfs=2024.2.0=pypi_0
gguf=0.6.0=pypi_0
gitdb=4.0.11=pypi_0
gitpython=3.1.43=pypi_0
google-api-core=2.18.0=pypi_0
google-auth=2.29.0=pypi_0
google-auth-oauthlib=1.2.0=pypi_0
google-cloud-core=2.4.1=pypi_0
google-cloud-storage=2.16.0=pypi_0
google-crc32c=1.5.0=pypi_0
google-resumable-media=2.7.0=pypi_0
googleapis-common-protos=1.63.0=pypi_0
gpustat=1.1.1=pypi_0
h11=0.14.0=pypi_0
hjson=3.1.0=pypi_0
htmlmin=0.1.12=pypi_0
httpcore=1.0.5=pypi_0
httpx=0.27.0=pypi_0
huggingface-hub=0.23.0=pypi_0
hydra-core=1.3.2=pypi_0
idna=3.6=pypi_0
imagehash=4.3.1=pypi_0
importlib-metadata=7.1.0=pypi_0
importlib-resources=6.4.0=pypi_0
ipykernel=6.23.1=pypi_0
ipython=8.18.1=pypi_0
ipywidgets=8.1.2=pypi_0
isoduration=20.11.0=pypi_0
jaxtyping=0.2.28=pypi_0
jedi=0.19.1=pypi_0
jinja2=3.1.3=pypi_0
joblib=1.3.2=pypi_0
json5=0.9.25=pypi_0
jsonpointer=2.4=pypi_0
jsonschema=4.21.1=pypi_0
jsonschema-specifications=2023.12.1=pypi_0
jupyter=1.0.0=pypi_0
jupyter-client=8.6.1=pypi_0
jupyter-console=6.6.3=pypi_0
jupyter-core=5.7.2=pypi_0
jupyter-events=0.10.0=pypi_0
jupyter-lsp=2.2.5=pypi_0
jupyter-server=2.14.0=pypi_0
jupyter-server-terminals=0.5.3=pypi_0
jupyterlab=4.1.6=pypi_0
jupyterlab-pygments=0.3.0=pypi_0
jupyterlab-server=2.27.1=pypi_0
jupyterlab-widgets=3.0.10=pypi_0
kiwisolver=1.4.5=pypi_0
ld_impl_linux-64=2.38=h1181459_1
libffi=3.4.4=h6a678d5_0
libgcc-ng=11.2.0=h1234567_1
libgomp=11.2.0=h1234567_1
libstdcxx-ng=11.2.0=h1234567_1
lit=15.0.7=pypi_0
llvmlite=0.42.0=pypi_0
markdown-it-py=3.0.0=pypi_0
markupsafe=2.1.5=pypi_0
matplotlib=3.3.0=pypi_0
matplotlib-inline=0.1.7=pypi_0
mdurl=0.1.2=pypi_0
mistune=3.0.2=pypi_0
mizani=0.11.1=pypi_0
mpmath=1.3.0=pypi_0
multidict=6.0.5=pypi_0
multimethod=1.11.2=pypi_0
multiprocess=0.70.16=pypi_0
mypy-extensions=1.0.0=pypi_0
natsort=8.4.0=pypi_0
nbclient=0.10.0=pypi_0
nbconvert=7.16.3=pypi_0
nbformat=5.10.4=pypi_0
ncurses=6.4=h6a678d5_0
nest-asyncio=1.6.0=pypi_0
networkx=3.2.1=pypi_0
ninja=1.11.1.1=pypi_0
nltk=3.8.1=pypi_0
notebook=7.1.3=pypi_0
notebook-shim=0.2.4=pypi_0
numba=0.59.1=pypi_0
numpy=1.26.4=pypi_0
nvidia-cublas-cu11=11.11.3.6=pypi_0
nvidia-cublas-cu12=12.1.3.1=pypi_0
nvidia-cuda-cupti-cu11=11.8.87=pypi_0
nvidia-cuda-cupti-cu12=12.1.105=pypi_0
nvidia-cuda-nvrtc-cu11=11.8.89=pypi_0
nvidia-cuda-nvrtc-cu12=12.1.105=pypi_0
nvidia-cuda-runtime-cu11=11.8.89=pypi_0
nvidia-cuda-runtime-cu12=12.1.105=pypi_0
nvidia-cudnn-cu11=8.7.0.84=pypi_0
nvidia-cudnn-cu12=8.9.2.26=pypi_0
nvidia-cufft-cu11=10.9.0.58=pypi_0
nvidia-cufft-cu12=11.0.2.54=pypi_0
nvidia-curand-cu11=10.3.0.86=pypi_0
nvidia-curand-cu12=10.3.2.106=pypi_0
nvidia-cusolver-cu11=11.4.1.48=pypi_0
nvidia-cusolver-cu12=11.4.5.107=pypi_0
nvidia-cusparse-cu11=11.7.5.86=pypi_0
nvidia-cusparse-cu12=12.1.0.106=pypi_0
nvidia-ml-py=12.535.133=pypi_0
nvidia-nccl-cu11=2.19.3=pypi_0
nvidia-nccl-cu12=2.19.3=pypi_0
nvidia-nvjitlink-cu12=12.4.127=pypi_0
nvidia-nvtx-cu11=11.8.86=pypi_0
nvidia-nvtx-cu12=12.1.105=pypi_0
oauthlib=3.2.2=pypi_0
omegaconf=2.3.0=pypi_0
openai=1.23.2=pypi_0
openpyxl=3.1.2=pypi_0
openssl=3.0.13=h7f8727e_0
overrides=7.7.0=pypi_0
packaging=24.0=pypi_0
pandas=2.2.1=pypi_0
pandocfilters=1.5.1=pypi_0
parso=0.8.4=pypi_0
pathtools=0.1.2=pypi_0
patsy=0.5.6=pypi_0
peft=0.10.0=pypi_0
pexpect=4.9.0=pypi_0
phik=0.12.4=pypi_0
pillow=10.3.0=pypi_0
pip=23.3.1=py39h06a4308_0
platformdirs=4.2.1=pypi_0
plotnine=0.13.4=pypi_0
prometheus-client=0.20.0=pypi_0
prompt-toolkit=3.0.43=pypi_0
proto-plus=1.23.0=pypi_0
protobuf=4.25.3=pypi_0
psutil=5.9.8=pypi_0
ptyprocess=0.7.0=pypi_0
pure-eval=0.2.2=pypi_0
py-cpuinfo=9.0.0=pypi_0
pyarrow=15.0.2=pypi_0
pyarrow-hotfix=0.6=pypi_0
pyasn1=0.6.0=pypi_0
pyasn1-modules=0.4.0=pypi_0
pycparser=2.22=pypi_0
pydantic=2.6.4=pypi_0
pydantic-core=2.16.3=pypi_0
pygments=2.17.2=pypi_0
pynvml=11.5.0=pypi_0
pyparsing=3.1.2=pypi_0
pyreft=0.0.5=pypi_0
python=3.9.19=h955ad1f_0
python-dateutil=2.9.0.post0=pypi_0
python-json-logger=2.0.7=pypi_0
pytz=2024.1=pypi_0
pyvene=0.1.1=pypi_0
pywavelets=1.6.0=pypi_0
pyyaml=6.0.1=pypi_0
pyzmq=26.0.2=pypi_0
qtconsole=5.5.1=pypi_0
qtpy=2.4.1=pypi_0
qwikidata=0.4.2=pypi_0
readline=8.2=h5eee18b_0
referencing=0.35.0=pypi_0
regex=2023.12.25=pypi_0
repe=0.1=dev_0
requests=2.31.0=pypi_0
requests-oauthlib=2.0.0=pypi_0
responses=0.18.0=pypi_0
rfc3339-validator=0.1.4=pypi_0
rfc3986-validator=0.1.1=pypi_0
rich=13.7.1=pypi_0
rouge=1.0.1=pypi_0
rouge-score=0.1.2=pypi_0
rpds-py=0.18.0=pypi_0
rsa=4.9=pypi_0
safetensors=0.4.2=pypi_0
scikit-learn=1.4.2=pypi_0
scipy=1.11.4=pypi_0
seaborn=0.12.2=pypi_0
send2trash=1.8.3=pypi_0
sentencepiece=0.2.0=pypi_0
sentry-sdk=1.44.1=pypi_0
setproctitle=1.3.3=pypi_0
setuptools=68.2.2=py39h06a4308_0
shtab=1.7.1=pypi_0
six=1.16.0=pypi_0
smmap=5.0.1=pypi_0
sniffio=1.3.1=pypi_0
soupsieve=2.5=pypi_0
sqlite=3.41.2=h5eee18b_0
stack-data=0.6.3=pypi_0
statsmodels=0.14.2=pypi_0
sympy=1.12=pypi_0
tabulate=0.9.0=pypi_0
tensor-parallel=1.2.4=pypi_0
terminado=0.18.1=pypi_0
threadpoolctl=3.4.0=pypi_0
tinycss2=1.3.0=pypi_0
tk=8.6.12=h1ccaba5_0
tokenizers=0.19.1=pypi_0
tomli=2.0.1=pypi_0
torch=2.1.2+cu118=pypi_0
torchaudio=2.1.2+cu118=pypi_0
torchvision=0.16.2+cu118=pypi_0
tornado=6.4=pypi_0
tqdm=4.66.2=pypi_0
traitlets=5.14.3=pypi_0
transformer-lens=1.12.0=pypi_0
transformers=4.40.0=pypi_0
triton=2.1.0=pypi_0
trl=0.8.6=pypi_0
typeguard=4.2.1=pypi_0
types-python-dateutil=2.9.0.20240316=pypi_0
typing-extensions=4.11.0=pypi_0
tyro=0.8.3=pypi_0
tzdata=2024.1=pypi_0
uri-template=1.3.0=pypi_0
urllib3=2.2.1=pypi_0
visions=0.7.6=pypi_0
wandb=0.15.3=pypi_0
wcwidth=0.2.13=pypi_0
webcolors=1.13=pypi_0
webencodings=0.5.1=pypi_0
websocket-client=1.8.0=pypi_0
wheel=0.41.2=py39h06a4308_0
widgetsnbextension=4.0.10=pypi_0
wikipedia=1.4.0=pypi_0
wordcloud=1.9.3=pypi_0
xxhash=3.4.1=pypi_0
xz=5.4.6=h5eee18b_0
yarl=1.9.4=pypi_0
ydata-profiling=4.7.0=pypi_0
zipp=3.18.1=pypi_0
zlib=1.2.13=h5eee18b_0

```

**Comment by stefanvasilev** [comment]
Do you maybe have run logs for the baseline without finetuning of llama3 or phi3?

**Comment by jinzhuoran** [comment]
[llama3_8b_instruct_1_Stephen_King.log](https://github.com/user-attachments/files/16495291/llama3_8b_instruct_1_Stephen_King.log)
Please refer to the attached file.

**Comment by stefanvasilev** [comment]
Hello, @jinzhuoran. I tried with your environment snapshot. Now I am getting the same log messages, however, there was a discrepancy in the eot_token_id. Yours is `128001` and mine was `128009`. I fixed this, but I am still getting the same results as before. 

Could you send the full json with the resutls for Stephen King (including the "results" key)?

**Comment by jinzhuoran** [comment]
I've included the full JSON ([forget.json](https://github.com/user-attachments/files/16509299/forget.json)) with the results for Stephen King.
Besides, I have uploaded the [config.json](https://github.com/user-attachments/files/16509462/config.json) and [tokenizer_config.json](https://github.com/user-attachments/files/16509464/tokenizer_config.json). Please try my file.

**Comment by jinzhuoran** [comment]
Hi @stefanvasilev. I seem to have discovered the issue. It looks like the tokenizer for llama3 was updated at some point, and I'm using the older version (https://huggingface.co/NousResearch/Meta-Llama-3-8B-Instruct/commit/3cf58932fb9b7257157a1a7e4b4cf0a469b069ba#d2h-846292). Could you please try using my [tokenizer.json](https://github.com/user-attachments/files/16511762/tokenizer.json)?

**Comment by jinzhuoran** [comment]
I use the new tokenizer.json and get the same result as yours.

**Comment by stefanvasilev** [comment]
Oh, that's great! I was looking into the tokeniser and saw that an incorrect eos token had been set at the past, but that was not the issue. 

I just tried your solution and now I am getting your results! However, I get them with this commit: https://huggingface.co/NousResearch/Meta-Llama-3-8B-Instruct/commit/4c78467aced3bc0088de25626bacf4f690ef4f9d, instead of the one you suggested.

Thanks for the help!

**Comment by stefanvasilev** [comment]
I assume the difference in results for Phi3 likely is due to the same reason, because in the commits of the phi3 repo I see changes to the tokenizer. I can confirm that later.

**Comment by jinzhuoran** [comment]
Yep, please also pay attention to the template of Phi3.

**Comment by stefanvasilev** [comment]
Hello, I didn't have a successful reproduction of the Phi3 results. Do you have the exact tokeniser used?

**Comment by stefanvasilev** [comment]
I can confirm now that I reproduced the Phi3 results with this commit:
https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/commit/d269012bea6fbe38ce7752c8940fea010eea3383

**Comment by stefanvasilev** [comment]
Hello, just wanted to ask if you are aware why do the results with the new LLama 3 tokenizer are worse than the old one? 
> I use the new tokenizer.json and get the same result as yours.

It makes sense that if the LLama repo authors will update the tokenizer it would perform better.

**Comment by stefanvasilev** [comment]
So it seems like the new LLama 3 tokenizer adds automatically the BOS token when tokenizing, so in [generate_completions()](https://github.com/jinzhuoran/RWKU/blob/c92b462e64875573422c3a6f3a75fea26f370ae5/LLaMA-Factory/src/llmtuner/eval/inference.py#L25) when setting `tokenizer(..., add_special_tokens=True)` we get a double BOS token in the encoded sequences, so: `{"input_ids": [12800, 12800, 128006, 882, ...], ...}`. That results in slight performance degradation.

**Comment by jinzhuoran** [comment]
Additionally, I filtered out the questions that were difficult for Llama 3 to answer correctly when selecting the probes. At that time, I was using an older version of the tokenizer.

**Comment by stefanvasilev** [comment]
Thanks, I think we can close this.
