### ISSUE TITLE
About the calculation of metrics

### ISSUE THREAD

**Issue by LetheSec** [jinzhuoran/RWKU#4]
Hi, thanks for the great work.

I would like to know how the values ​​of "MIA Set" and "Flu" in the table are reported with the obtained results.

https://github.com/jinzhuoran/RWKU/issues/3#issuecomment-2268901311
For example, "Loss -2.492", "Loss -2.370" and "Entropy 6.978" in the above file.

**Comment by jinzhuoran** [comment]
Hi @LetheSec, for the MIA Set, we report Loss * -100, and for the Flu, we report Entropy * 100.

**Comment by LetheSec** [comment]
Thank you for your reply.
