### ISSUE TITLE
code for adversary attack

### ISSUE THREAD

**Issue by pkulium** [jinzhuoran/RWKU#5]
great work! Can we get code for adversary attack?

**Comment by jinzhuoran** [comment]
Hello, are you referring to the code for generating adversarial attack probes? We generated it by prompting GPT-4.

**Comment by pkulium** [comment]
Thanks for reply. Is there code to reproduce results in Figure 4: Comparison of different adversarial attack types on LLaMA3-Instruct (8B)?

**Comment by jinzhuoran** [comment]
You need to first run the provided scripts for various unlearning methods to obtain experimental results, such as `bash scripts/full/run_ga.sh`. Are you referring to the code for plotting?
